name: GitHub Actions 
run-name: ${{ github.actor }} is running App
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: Build with Gradle
      run: make build
